# Generated by Django 5.0.1 on 2024-01-23 02:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_bankaccount_transactions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="transactions",
        ),
    ]
