# Generated by Django 5.0.1 on 2024-01-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_remove_bankaccount_transactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="transactions",
            field=models.TextField(default="[]"),
        ),
    ]
