# Generated by Django 5.0.1 on 2024-01-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_bankaccount_transactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="encoded_face",
            field=models.TextField(default="null"),
        ),
    ]
