# Generated by Django 5.0.1 on 2024-01-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_bankaccount_encoded_face"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="encoded_face",
            field=models.TextField(),
        ),
    ]
