# Generated by Django 5.0.1 on 2024-01-31 03:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_alter_bankaccount_encoded_face"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="encoded_face",
        ),
    ]
