# Generated by Django 5.0.1 on 2024-01-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_remove_bankaccount_encoded_face"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("original_image", models.ImageField(upload_to="user_images/")),
                ("encoded_image", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
