# Generated by Django 5.0.1 on 2024-01-31 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_userimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userimage",
            old_name="encoded_image",
            new_name="facial_features",
        ),
    ]
