# Generated by Django 5.0.1 on 2024-01-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_rename_encoded_image_userimage_facial_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryFaceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(upload_to="temporary_face_images/"),
                ),
            ],
        ),
    ]
